//! I/O front-end for the multi-shard driver topology.
//!
//! Phase 02 follow-up (`plans-27-webrtc-zlm2/phase-02-driver-multithread-shard.md`).
//!
//! When `WebRtcDriverConfig::effective_shard_count() > 1` the driver
//! is split into:
//!
//! * one `WebRtcIoFront` task that owns the UDP/TCP listeners, the
//!   command receiver, and the route directory;
//! * `N` `run_shard_loop` tasks, each owning a `WebRtcCore` plus
//!   shard-local `RouteTable`, watchdog state, command and packet
//!   receivers.
//!
//! The front-end forwards inbound datagrams to the shard that owns
//! the source address (via the directory) or, for unbound packets,
//! the ufrag-resolved or first-accepting shard. Commands are routed
//! to the owner shard (`AcceptOffer`/`CreateOffer` use the
//! `ShardSelector`; everything else uses the directory).
//!
//! The single-shard fast path stays in `runner.rs::run_driver_core`
//! to preserve existing test guarantees and simplify the control flow
//! when no horizontal scaling is needed.

use std::sync::Arc;

use cheetah_runtime_api::CancellationToken;
use cheetah_webrtc_core::WebRtcSessionId;
use tokio::sync::mpsc;
use tracing::{debug, info, warn};

use crate::config::WebRtcDriverConfig;
use crate::directory::{RouteDirectory, ShardCandidateTable, ShardId};
use crate::runner::{
    NetDatagram, ShardCommand, TcpWriterRegistry, WebRtcDriverCommand, WebRtcDriverDiagnostic,
    WebRtcDriverDiagnosticKind, WebRtcDriverEvent,
};
use crate::shard::{ShardLoadTable, ShardSelector};
use crate::stun::extract_local_ufrag;
/// Per-shard channel handles owned by the front-end.
///
/// Senders are wrapped in [`parking_lot::RwLock`] so the supervisor
/// can swap them when respawning a panicked shard. The front-end's
/// dispatch path takes a read lock per send, so contention with the
/// (rare) supervisor write is bounded; tests show the read lock
/// adds <100 ns per send relative to the previous unsynchronised
/// `mpsc::Sender` clone.
pub(crate) struct ShardChannels {
    pub(crate) cmd_tx: parking_lot::RwLock<mpsc::Sender<ShardCommand>>,
    pub(crate) packet_tx: parking_lot::RwLock<mpsc::Sender<NetDatagram>>,
}

impl ShardChannels {
    pub(crate) fn new(
        cmd_tx: mpsc::Sender<ShardCommand>,
        packet_tx: mpsc::Sender<NetDatagram>,
    ) -> Self {
        Self {
            cmd_tx: parking_lot::RwLock::new(cmd_tx),
            packet_tx: parking_lot::RwLock::new(packet_tx),
        }
    }

    pub(crate) fn cmd_sender(&self) -> mpsc::Sender<ShardCommand> {
        self.cmd_tx.read().clone()
    }

    pub(crate) fn packet_sender(&self) -> mpsc::Sender<NetDatagram> {
        self.packet_tx.read().clone()
    }

    pub(crate) fn rebind(
        &self,
        cmd_tx: mpsc::Sender<ShardCommand>,
        packet_tx: mpsc::Sender<NetDatagram>,
    ) {
        *self.cmd_tx.write() = cmd_tx;
        *self.packet_tx.write() = packet_tx;
    }
}

/// Forward a datagram to the shard that owns its source address.
/// Falls back to ufrag-based lookup. When neither resolves, the
/// front-end emits an `UnroutedPacket` diagnostic and bumps the
/// unrouted counter — there is no shard that could accept the packet
/// because the directory has not seen this peer or this ufrag.
///
/// In the multi-shard topology shards register their local ufrag
/// with the directory before the remote peer can learn it (the SDP
/// containing the ufrag is generated by the shard and only surfaces
/// to the remote after `LocalDescription` is drained — at which
/// point the ufrag is already in the directory). So a STUN binding
/// request that doesn't match any registered ufrag is, by
/// construction, not for any active session.
pub(crate) async fn dispatch_datagram(
    datagram: NetDatagram,
    shards: &[Arc<ShardChannels>],
    directory: &RouteDirectory,
    event_tx: &mpsc::Sender<WebRtcDriverEvent>,
    unrouted_packets: &Arc<std::sync::atomic::AtomicU64>,
) {
    let source = datagram.source();
    if shards.is_empty() {
        unrouted_packets.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        return;
    }

    // Fast path: known address → owner shard.
    if let Some((_, shard)) = directory.lookup_remote(&source) {
        if let Some(channel) = shards.get(shard.as_usize()) {
            send_or_drop(channel, datagram, event_tx, unrouted_packets, "addr-bound").await;
            return;
        }
    }

    // STUN binding request: extract local ufrag and look up the shard
    // that registered it.
    if let Some(ufrag) = extract_local_ufrag(datagram.data()) {
        if let Some(shard) = directory.lookup_ufrag(&ufrag) {
            if let Some(channel) = shards.get(shard.as_usize()) {
                send_or_drop(channel, datagram, event_tx, unrouted_packets, "ufrag").await;
                return;
            }
        }
    }

    // No directory binding for this address or ufrag. The packet is
    // truly unrouted; surface the diagnostic so operators can see
    // unexpected traffic and bump the counter for stats.
    let packet_len = datagram.data().len();
    unrouted_packets.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let _ = event_tx
        .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
            session_id: None,
            kind: WebRtcDriverDiagnosticKind::UnroutedPacket,
            message: format!("dropped {packet_len} byte packet from {source}"),
        }))
        .await;
}

async fn send_or_drop(
    shard: &ShardChannels,
    datagram: NetDatagram,
    event_tx: &mpsc::Sender<WebRtcDriverEvent>,
    unrouted_packets: &Arc<std::sync::atomic::AtomicU64>,
    reason: &'static str,
) {
    let sender = shard.packet_sender();
    if let Err(err) = sender.try_send(datagram) {
        match err {
            mpsc::error::TrySendError::Full(_) => {
                unrouted_packets.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                let _ = event_tx
                    .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
                        session_id: None,
                        kind: WebRtcDriverDiagnosticKind::QueueFull,
                        message: format!("shard packet queue full ({reason}); packet dropped"),
                    }))
                    .await;
            }
            mpsc::error::TrySendError::Closed(_) => {
                debug!("shard packet channel closed during {reason} dispatch");
            }
        }
    }
}

/// Forward a command to the shard that owns the target session.
///
/// New-session commands (`AcceptOffer`/`CreateOffer`) use the
/// configured [`ShardSelector`]. All other commands look up the
/// owner via the directory; when a session is unknown we surface a
/// diagnostic and drop the command rather than guessing.
pub(crate) async fn dispatch_command(
    cmd: WebRtcDriverCommand,
    shards: &[Arc<ShardChannels>],
    directory: &RouteDirectory,
    selector: &ShardSelector,
    loads: &ShardLoadTable,
    event_tx: &mpsc::Sender<WebRtcDriverEvent>,
) {
    if shards.is_empty() {
        warn!("no shards available; dropping driver command");
        return;
    }
    let (target_shard, owned_command) = match cmd {
        WebRtcDriverCommand::AcceptOffer(spec) => {
            let shard = selector.pick(spec.session_id, loads);
            (
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::AcceptOffer(spec)),
            )
        }
        WebRtcDriverCommand::CreateOffer {
            session_id,
            role,
            spec,
            candidate_transport_policy,
        } => {
            let shard = selector.pick(session_id, loads);
            (
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::CreateOffer {
                    session_id,
                    role,
                    spec,
                    candidate_transport_policy,
                }),
            )
        }
        WebRtcDriverCommand::AddRemoteCandidate {
            session_id,
            candidate,
        } => {
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::AddRemoteCandidate {
                    session_id,
                    candidate,
                }),
                shards,
                event_tx,
                "AddRemoteCandidate",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::IceRestart {
            session_id,
            keep_local_candidates,
        } => {
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::IceRestart {
                    session_id,
                    keep_local_candidates,
                }),
                shards,
                event_tx,
                "IceRestart",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::ApplyRemoteAnswer {
            session_id,
            remote_sdp,
        } => {
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::ApplyRemoteAnswer {
                    session_id,
                    remote_sdp,
                }),
                shards,
                event_tx,
                "ApplyRemoteAnswer",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::SendFrame(frame) => {
            let session_id = frame.session_id;
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::SendFrame(frame)),
                shards,
                event_tx,
                "SendFrame",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::SendDataChannel(out) => {
            let session_id = out.session_id;
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::SendDataChannel(out)),
                shards,
                event_tx,
                "SendDataChannel",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::RequestKeyframe {
            session_id,
            mid,
            kind,
        } => {
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::RequestKeyframe {
                    session_id,
                    mid,
                    kind,
                }),
                shards,
                event_tx,
                "RequestKeyframe",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::StopSession { session_id, reason } => {
            let shard = directory.lookup_session(session_id);
            forward_for_session(
                session_id,
                shard,
                ShardCommand::Driver(WebRtcDriverCommand::StopSession { session_id, reason }),
                shards,
                event_tx,
                "StopSession",
            )
            .await;
            return;
        }
        WebRtcDriverCommand::PanicShard { shard_id } => (shard_id, ShardCommand::Panic),
    };

    if let Some(channel) = shards.get(target_shard.as_usize()) {
        let sender = channel.cmd_sender();
        if let Err(err) = sender.send(owned_command).await {
            warn!("shard {target_shard} command channel closed: {err}");
        }
    } else {
        warn!(
            "shard selector returned out-of-range index {target_shard}; \
             dropping command"
        );
    }
}

async fn forward_for_session(
    session_id: WebRtcSessionId,
    shard: Option<ShardId>,
    cmd: ShardCommand,
    shards: &[Arc<ShardChannels>],
    event_tx: &mpsc::Sender<WebRtcDriverEvent>,
    label: &'static str,
) {
    let Some(shard) = shard else {
        // Unknown session — surface a diagnostic so operators can
        // distinguish "command before session" from a silent drop.
        let _ = event_tx
            .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
                session_id: Some(session_id),
                kind: WebRtcDriverDiagnosticKind::Lifecycle,
                message: format!(
                    "{label} for unknown session {session_id} \
                     (no directory entry); command dropped"
                ),
            }))
            .await;
        return;
    };
    let Some(channel) = shards.get(shard.as_usize()) else {
        warn!(
            "directory returned out-of-range shard {shard} for session \
             {session_id}; dropping {label}"
        );
        return;
    };
    if let Err(err) = channel.cmd_sender().send(cmd).await {
        warn!(
            "shard {shard} command channel closed while forwarding \
             {label} for session {session_id}: {err}"
        );
    }
}

/// Configuration passed from `spawn_driver` into the front-end task.
pub(crate) struct IoFrontConfig {
    pub(crate) shards: Vec<Arc<ShardChannels>>,
    pub(crate) directory: Arc<RouteDirectory>,
    pub(crate) selector: ShardSelector,
    pub(crate) shard_loads: Arc<ShardLoadTable>,
    pub(crate) commands_accepted: Arc<std::sync::atomic::AtomicU64>,
    pub(crate) unrouted_packets: Arc<std::sync::atomic::AtomicU64>,
    pub(crate) event_tx: mpsc::Sender<WebRtcDriverEvent>,
    pub(crate) cmd_rx: mpsc::Receiver<WebRtcDriverCommand>,
    pub(crate) packet_rx: mpsc::Receiver<NetDatagram>,
}

/// Run the I/O front-end: route inbound datagrams and commands to
/// shards, surface backpressure diagnostics, and exit on cancellation.
pub(crate) async fn run_io_front(mut cfg: IoFrontConfig, cancel: CancellationToken) {
    info!(
        "WebRTC multi-shard front-end running with {} shards",
        cfg.shards.len()
    );
    loop {
        tokio::select! {
            biased;
            _ = cancel.cancelled() => {
                info!("WebRTC multi-shard front-end cancelled");
                break;
            }
            cmd = cfg.cmd_rx.recv() => {
                match cmd {
                    Some(cmd) => {
                        cfg.commands_accepted
                            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                        dispatch_command(
                            cmd,
                            &cfg.shards,
                            &cfg.directory,
                            &cfg.selector,
                            &cfg.shard_loads,
                            &cfg.event_tx,
                        )
                        .await;
                    }
                    None => {
                        info!("WebRTC front-end command channel closed; exiting");
                        break;
                    }
                }
            }
            datagram = cfg.packet_rx.recv() => {
                match datagram {
                    Some(datagram) => {
                        dispatch_datagram(
                            datagram,
                            &cfg.shards,
                            &cfg.directory,
                            &cfg.event_tx,
                            &cfg.unrouted_packets,
                        ).await;
                    }
                    None => {
                        info!("WebRTC front-end packet channel closed; exiting");
                        break;
                    }
                }
            }
        }
    }
}

/// Build per-shard channels and spawn `N` shard tasks. Returns the
/// front-end channels so `spawn_driver` can wire them in.
///
/// Each shard task is wrapped in a supervisor that emits a
/// [`WebRtcDriverEvent::ShardStopped`] when the inner future exits
/// (either by graceful cancellation or panic).
///
/// When `config.shard_restart_on_panic` is `true` the supervisor
/// also runs the equivalent of [`WebRtcDriverHandle::evict_shard`]
/// after a panic: directory entries owned by the dead shard are
/// removed, the TCP writer registry is cascaded so writers owned
/// by the dead shard release their sockets immediately, the
/// per-shard load counters reset, and a `Lifecycle` diagnostic
/// surfaces the eviction stats (including the cleaned writer
/// count as `tcp_writers={N}`). The shard task itself
/// is **not** auto-respawned — re-binding the front-end's senders
/// to a fresh receiver requires invasive plumbing that's out of
/// scope here. Auto-eviction is enough to unblock further driver
/// operation: new sessions selector-routed to the dead shard will
/// see `QueueFull` (sender stale) and the operator can decide
/// whether to bring up a fresh driver instance.
#[allow(clippy::too_many_arguments)]
pub(crate) fn spawn_shards(
    config: &WebRtcDriverConfig,
    shard_count: usize,
    udp_socket: Arc<tokio::net::UdpSocket>,
    tcp_writers: Arc<TcpWriterRegistry>,
    event_tx: mpsc::Sender<WebRtcDriverEvent>,
    cancel: CancellationToken,
    session_count: Arc<std::sync::atomic::AtomicUsize>,
    unrouted_packets: Arc<std::sync::atomic::AtomicU64>,
    route_directory: Arc<RouteDirectory>,
    shard_loads: Arc<ShardLoadTable>,
    shard_candidates: Arc<ShardCandidateTable>,
) -> Vec<Arc<ShardChannels>> {
    let mut channels = Vec::with_capacity(shard_count);
    let cmd_capacity = config.shard_command_capacity.max(16);
    let pkt_capacity = config.write_queue_capacity.max(64);
    let auto_evict = config.shard_restart_on_panic;
    let max_restarts = config.shard_max_restart_count;
    let initial_backoff_ms = config.shard_restart_backoff_ms;
    let max_backoff_ms = config.shard_max_restart_backoff_ms;
    for shard_index in 0..shard_count {
        let shard_id = ShardId::new(shard_index);
        let (cmd_tx, cmd_rx_initial) = mpsc::channel::<ShardCommand>(cmd_capacity);
        let (pkt_tx, pkt_rx_initial) = mpsc::channel::<NetDatagram>(pkt_capacity);
        let shard_channels = Arc::new(ShardChannels::new(cmd_tx, pkt_tx));
        channels.push(shard_channels.clone());

        let cfg = config.clone();
        let socket = udp_socket.clone();
        let writers = tcp_writers.clone();
        let event_tx_supervisor = event_tx.clone();
        let cancel_supervisor = cancel.clone();
        let session_count_supervisor = session_count.clone();
        let unrouted_packets_supervisor = unrouted_packets.clone();
        let directory_supervisor = route_directory.clone();
        let loads_supervisor = shard_loads.clone();
        let candidates_supervisor = shard_candidates.clone();
        let channels_for_supervisor = shard_channels.clone();

        // Supervisor task: spawns the shard loop, awaits its
        // termination, and (when configured) auto-restarts on
        // panic. Channel rebind happens on respawn so the
        // front-end's senders (held inside `Arc<ShardChannels>`)
        // start routing into the freshly-spawned receiver.
        tokio::spawn(async move {
            let mut cmd_rx = Some(cmd_rx_initial);
            let mut pkt_rx = Some(pkt_rx_initial);
            let mut restarts: u32 = 0;
            let mut backoff_ms = initial_backoff_ms;
            loop {
                let cmd_rx_owned = cmd_rx
                    .take()
                    .expect("shard command receiver must be present at top of loop");
                let pkt_rx_owned = pkt_rx
                    .take()
                    .expect("shard packet receiver must be present at top of loop");

                let cfg_inner = cfg.clone();
                let socket_inner = socket.clone();
                let writers_inner = writers.clone();
                let event_tx_inner = event_tx_supervisor.clone();
                let cancel_inner = cancel_supervisor.clone();
                let session_count_inner = session_count_supervisor.clone();
                let unrouted_packets_inner = unrouted_packets_supervisor.clone();
                let directory_inner = directory_supervisor.clone();
                let loads_inner = loads_supervisor.clone();
                let candidates_inner = candidates_supervisor.clone();
                let inner = tokio::spawn(async move {
                    crate::runner::run_shard_loop(
                        shard_id,
                        cfg_inner,
                        socket_inner,
                        writers_inner,
                        cmd_rx_owned,
                        pkt_rx_owned,
                        event_tx_inner,
                        cancel_inner,
                        session_count_inner,
                        unrouted_packets_inner,
                        directory_inner,
                        loads_inner,
                        candidates_inner,
                    )
                    .await;
                });

                let join_result = inner.await;
                let cancelled = cancel_supervisor.is_cancelled();
                let (reason, panicked) = match join_result {
                    Ok(()) => {
                        let r = if cancelled {
                            "cancelled".to_string()
                        } else {
                            "exited".to_string()
                        };
                        (r, false)
                    }
                    Err(err) if err.is_cancelled() => ("task cancelled".to_string(), false),
                    Err(err) if err.is_panic() => (format!("panic: {err}"), true),
                    Err(err) => (format!("join error: {err}"), false),
                };
                let _ = event_tx_supervisor
                    .send(WebRtcDriverEvent::ShardStopped {
                        shard_id,
                        reason: reason.clone(),
                    })
                    .await;

                // Auto-eviction: when enabled and the shard
                // panicked, clean up directory + load counters so
                // future sessions don't race ghost mappings. The
                // TCP writer registry is also cascaded so any
                // connections owned by the dead shard release
                // their sockets immediately instead of waiting
                // for per-connection idle timeouts (mirrors
                // [`WebRtcDriverHandle::evict_shard`]).
                if auto_evict && panicked && !cancelled {
                    let mut evicted = directory_supervisor.forget_shard(shard_id);
                    let tcp_evicted = writers.forget_shard(shard_id);
                    evicted.tcp_writers = tcp_evicted;
                    loads_supervisor.record_route_counts(shard_id, 0, 0);
                    for _ in 0..evicted.sessions {
                        loads_supervisor.record_session_removed(shard_id);
                    }
                    // Reset the per-shard candidate gauge so
                    // operator-visible `shard_candidate_stats()`
                    // does not keep reporting the panicked shard's
                    // last gathered counts. Graceful exits skip
                    // this so a clean shutdown preserves the final
                    // observed counts for postmortem.
                    candidates_supervisor.clear_shard(shard_id);
                    let prev = session_count_supervisor.load(std::sync::atomic::Ordering::Relaxed);
                    let new = prev.saturating_sub(evicted.sessions);
                    session_count_supervisor.store(new, std::sync::atomic::Ordering::Relaxed);
                    let _ = event_tx_supervisor
                        .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
                            session_id: None,
                            kind: WebRtcDriverDiagnosticKind::Lifecycle,
                            message: format!(
                                "shard {shard_id} auto-evicted after panic: \
                                 sessions={} addresses={} ufrags={} stale={} tcp_writers={}",
                                evicted.sessions,
                                evicted.addresses,
                                evicted.ufrags,
                                evicted.stale,
                                evicted.tcp_writers
                            ),
                        }))
                        .await;
                }

                // Decide whether to respawn. Conditions for stop:
                // cancellation, restart disabled, non-panic exit,
                // or restart budget exhausted.
                if cancelled || !auto_evict || !panicked || restarts >= max_restarts {
                    if panicked && auto_evict && restarts >= max_restarts {
                        let _ = event_tx_supervisor
                            .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
                                session_id: None,
                                kind: WebRtcDriverDiagnosticKind::Lifecycle,
                                message: format!(
                                    "shard {shard_id} reached max_restart_count={max_restarts}; \
                                     not respawning"
                                ),
                            }))
                            .await;
                    }
                    break;
                }

                // Backoff before respawn so a tight panic loop
                // doesn't burn the runner.
                tokio::time::sleep(std::time::Duration::from_millis(backoff_ms)).await;
                backoff_ms = backoff_ms.saturating_mul(2).min(max_backoff_ms);
                restarts = restarts.saturating_add(1);

                // Build fresh channels and rebind the front-end's
                // shared `Arc<ShardChannels>` so subsequent sends
                // route into the new shard task's receivers.
                let (new_cmd_tx, new_cmd_rx) = mpsc::channel::<ShardCommand>(cmd_capacity);
                let (new_pkt_tx, new_pkt_rx) = mpsc::channel::<NetDatagram>(pkt_capacity);
                channels_for_supervisor.rebind(new_cmd_tx, new_pkt_tx);
                cmd_rx = Some(new_cmd_rx);
                pkt_rx = Some(new_pkt_rx);
                let _ = event_tx_supervisor
                    .send(WebRtcDriverEvent::Diagnostic(WebRtcDriverDiagnostic {
                        session_id: None,
                        kind: WebRtcDriverDiagnosticKind::Lifecycle,
                        message: format!(
                            "shard {shard_id} respawning attempt {restarts}/{max_restarts} \
                             (backoff next {backoff_ms}ms)"
                        ),
                    }))
                    .await;
            }
        });
    }
    channels
}
