//! Output items emitted by the core.
//!
//! `WebRtcCoreOutput` is the only way the Sans-I/O state machine requests an
//! action from the driver. The driver is responsible for converting these
//! values into socket sends, timer arms, HTTP responses, and engine calls.
//!
//! 本模块包含核心产生的输出项。
//!
//! `WebRtcCoreOutput` 是 Sans-I/O 状态机请求驱动层执行动作的唯一方式。
//! 驱动层负责将这些值转换为 socket 发送、定时器设置、HTTP 响应与引擎调用。

use std::net::SocketAddr;

use bytes::Bytes;
use serde::{Deserialize, Serialize};

use crate::error::WebRtcCoreDiagnostic;
use crate::event::WebRtcCoreEvent;
use crate::input::WebRtcCloseReason;
use crate::types::WebRtcSessionId;

/// Actions produced by the core for the driver layer.
///
/// The enum is a flattened, deterministic command stream. It does not contain
/// any runtime-specific types, so the driver can be implemented on tokio,
/// a test harness, or a different executor.
///
/// 核心为驱动层产生的动作。
///
/// 该枚举是扁平、确定性的命令流。它不包含任何运行时专用类型，因此驱动层
/// 可以基于 tokio、测试套件或不同执行器实现。
#[derive(Debug, Clone)]
pub enum WebRtcCoreOutput {
    /// Network packet to deliver via the driver socket.
    ///
    /// 通过驱动 socket 发送的网络包。
    SendPacket(WebRtcPacketOut),
    /// Driver should arm a timer for the given deadline.
    ///
    /// Subsequent `SetTimer` for the same session supersede earlier ones.
    ///
    /// 驱动层应为给定的截止时间设置定时器。
    ///
    /// 同一会话的后续 `SetTimer` 会覆盖之前的定时器。
    SetTimer(WebRtcTimer),
    /// Session emitted a state-machine event.
    ///
    /// 会话发出状态机事件。
    Event(WebRtcCoreEvent),
    /// Diagnostic record (non-fatal observation).
    ///
    /// 诊断记录（非致命观察）。
    Diagnostic(WebRtcCoreDiagnostic),
    /// Local SDP description ready (offer or answer).
    ///
    /// 本地 SDP 描述已就绪（offer 或 answer）。
    LocalDescription {
        session_id: WebRtcSessionId,
        sdp: String,
        kind: WebRtcLocalDescriptionKind,
    },
    /// The driver should release this session and any associated state.
    ///
    /// 驱动层应释放本会话及任何相关状态。
    CloseSession {
        session_id: WebRtcSessionId,
        reason: WebRtcCloseReason,
    },
}

/// Kind of local SDP description produced by the core.
///
/// Distinguishes an offer created by `CreateOffer` / `IceRestart` from an
/// answer generated by `AcceptOffer`.
///
/// 核心产生的本地 SDP 描述类型。
///
/// 区分 `CreateOffer` / `IceRestart` 创建的 offer 与 `AcceptOffer` 生成的 answer。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WebRtcLocalDescriptionKind {
    /// Local SDP offer.
    ///
    /// 本地 SDP offer。
    Offer,
    /// Local SDP answer.
    ///
    /// 本地 SDP answer。
    Answer,
}

/// A network packet the driver must send on behalf of a session.
///
/// `source` is `None` when `str0m` cannot determine which local socket
/// produced the packet; the driver should fall back to its own bound socket.
///
/// 驱动层需代表会话发送的网络包。
///
/// 当 `str0m` 无法确定哪个本地 socket 产生该包时，`source` 为 `None`；
/// 驱动层应回退到其绑定的 socket。
#[derive(Debug, Clone)]
pub struct WebRtcPacketOut {
    pub session_id: WebRtcSessionId,
    pub source: Option<SocketAddr>,
    pub destination: SocketAddr,
    pub data: Bytes,
}

/// Timer request produced by a session.
///
/// The deadline is in microseconds relative to the `start_instant` anchor
/// supplied to [`crate::WebRtcCore::new`]. The driver must re-invoke the
/// core with a `Timeout` input for that session at or before the deadline.
///
/// 会话产生的定时器请求。
///
/// 截止时间是相对于传入 [`crate::WebRtcCore::new`] 的 `start_instant` 锚点的
/// 微秒数。驱动层必须在截止时间或之前以该会话的 `Timeout` 输入重新调用核心。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WebRtcTimer {
    pub session_id: WebRtcSessionId,
    /// Deadline expressed in microseconds anchored at the core start time.
    ///
    /// 以核心启动时间为锚点的微秒截止时间。
    pub deadline_micros: u64,
}
