#!/usr/bin/env bash
# CL904-05: generate a release evidence markdown file with static supply-chain
# information. Run this on the release candidate build machine after all artifacts
# (x86_64/aarch64/container/SBOM/license/perf) have been produced, then attach
# the actual artifact URLs/checksums to the generated file before sign-off.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

COMMIT="$(git rev-parse HEAD)"
SHORT_COMMIT="$(git rev-parse --short HEAD)"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
CARGO_LOCK_SHA256="$(sha256sum Cargo.lock | cut -d' ' -f1)"
RUSTC_VERSION="$(rustc --version)"
CARGO_VERSION="$(cargo --version)"
OS_INFO="$(uname -s -r -v -m 2>/dev/null || uname -a)"
ARCH="$(uname -m)"

AVCODEC_REV="$(grep -oP 'avcodec-rs-develop\.git\?rev=\K[0-9a-f]+' Cargo.lock | head -1 || true)"
if [[ -z "$AVCODEC_REV" ]]; then
    AVCODEC_REV="not found"
fi

OUT_DIR="${1:-target/release_evidence}"
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/release_evidence_${SHORT_COMMIT}.md"

cat > "$OUT_FILE" <<EOF
# Release Evidence — Cheetah Media Server

> Generated by \`scripts/generate_cl904_05_evidence.sh\` at ${DATE}.
> Fill in artifact URLs and checksums before signing off CL904-05.

## 1. Candidate Version

| Field | Value |
| --- | --- |
| Cheetah commit | \`${COMMIT}\` |
| 904 evidence | in progress |
| signaling contract tag | *(blocked on CT-01 — not available yet)* |
| signaling full revision | *(blocked on CT-01 — not available yet)* |
| descriptor SHA-256 | *(blocked on CT-01 — not available yet)* |
| accepted/min/max contract version | *(blocked on CT-01 — not available yet)* |
| Rust/Cargo | \`${RUSTC_VERSION}\` / \`${CARGO_VERSION}\` |
| OS/arch | \`${OS_INFO}\` |
| Cargo.lock checksum | \`${CARGO_LOCK_SHA256}\` |
| SQLite schema version | *(managed by cheetah-media-control-plane migrations)* |
| x86_64 artifact/checksum | TBD |
| aarch64 artifact/checksum | TBD |
| container digest | TBD |
| SBOM | TBD |
| license report | TBD |
| avcodec full revision | \`${AVCODEC_REV}\` |
| test time/executor | ${DATE} / $(whoami) |

## 2. Feature and Dependency Profiles

Commands used for verification (evidence logs must be attached separately):

- C0: \`cargo check -p cheetah-server --no-default-features\`
- C1: \`cargo test -p cheetah-media-processing-module --features media-processing-audio\`
- C2: \`cargo test -p cheetah-media-processing-module --features media-processing-image\`
- C3: \`cargo test -p cheetah-media-processing-module --features media-processing-video\`
- C4: \`cargo test -p cheetah-media-processing-module --features media-processing-full\`
- C5: \`cargo test -p cheetah-server --features media-processing-full,rtmp,rtsp,http-flv,hls,ts,fmp4,mp4,rtp,gb28181,record,webrtc,srt,proxy,proxy-rtsp,proxy-rtmp,proxy-http-flv,snapshot\`
- C6: \`cargo build -p cheetah-server --release --features media-processing-full,rtmp,rtsp,http-flv,hls,ts,fmp4,mp4,rtp,gb28181,record,webrtc,srt,proxy,proxy-rtsp,proxy-rtmp,proxy-http-flv,snapshot\`

Checks:

- [ ] CL904-01 direct image removal — run \`./scripts/verify_cl904_01_image_cleanup.sh\`
- [ ] CL904-02 C0–C6 lane logs present
- [ ] CL904-03 five protocol E2E artifacts
- [ ] CL904-04 benchmark/24h soak report
- [ ] CL904-05 SBOM/license/evidence signed

## 3. Dependency Tree Snapshots

### C0 (no default features)

\`\`\`
$(cargo tree -p cheetah-server --no-default-features 2>&1 || true)
\`\`\`

### Signaling control plane

\`\`\`
$(cargo tree -p cheetah-server --features signaling-control-plane 2>&1 || true)
\`\`\`

## 4. Direct Dependency Audit

Direct third-party crates are declared only in workspace root \`Cargo.toml\` or crate manifests. No direct \`image\` crate dependency (verified by \`scripts/verify_cl904_01_image_cleanup.sh\`).

Avcodec is consumed only through the top-level \`avcodec\` crate at revision \`${AVCODEC_REV}\`.

## 5. Sign-off

| Role | Owner | Signature | Date |
| --- | --- | --- | --- |
| Release engineer | TBD | | |
| Security review | TBD | | |
| 904 closeout | TBD | | |

EOF

echo "Release evidence written to: $OUT_FILE"
